development:
  adapter: mysql
  database: tracks
  host: localhost
  username: tracks
  password: W7AD5ApasrvYB14r79OR

test: &TEST
    adapter: sqlite3
    database: ":memory:"

production:
  adapter: mysql
  database: tracks
  host: localhost
  username: foo
  password: bar

cucumber:
  <<: *TEST

selenium:
  <<: *TEST
